version: '3.6'

services:
  api:
    build: .
    depends_on:
      - db
      - db_tst
    env_file:
      - ./.env
    ports:
      - 3000:3000
    networks:
      - default
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    #   - ./src/database/migrations:/usr/src/app/src/database/migrations
    restart: always

  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    networks:
      - default
    ports:
      - 5198:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petshop_development
    restart: always

  db_tst:
    image: postgres:latest
    networks:
      - default
    ports:
      - 5199:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petshop_testing
    restart: always

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local