version: '3.7'

services:
  database:
    image: postgres
    container_name: petshop_database
    restart: always
    ports:
      - 5198:5432
    environment:
      - POSTGRES_USER=petshop
      - POSTGRES_PASSWORD=petshop
      - POSTGRES_DB=petshop_development
    volumes:
      - pgdata:/data/postgres
      - ./create_testing_db.sh:/docker-entrypoint-initdb.d/create_testing_db.sh

  app:
    build: .
    container_name: node_petshop
    ports:
      - 3333:3333
    links:
      - database
    depends_on:
      - database
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local
